#!/usr/bin/env python
import sys
sys.path.append("../asyncio")
sys.path.append("../xudd")
sys.path.append("../PyPump")
sys.path.append("../oauthlib")
sys.path.append("../requests-oauthlib")
sys.path.append("../dateutil")
import time

from xudd.hive import Hive
from xudd.tools import join_id
from pump import Pump
from controller import Controller
from ui import CLI

#from main import Pump
import time
import pprint
import pdb; 
from xudd.actor import Actor
from pypump import PyPump
from pypump.client import Client
def verifier_callback (url):
    print("Get callback" +url + "\n")
    print('Please follow the instructions at the following URL:')
    print(url)
    return input("Verifier: ") # the verifier is a string


if __name__ == "__main__":
    webfinger = sys.argv[1]
    #p = Pump(hive="tst",id="bba",webfinger=webfinger)
    #m = {}
    #p.setup(m)
    client = Client(
        webfinger,
        name="Muon",
        type="native"                
    )
    pprint.pprint({"before pump":client.__dict__})
    
    pump = PyPump(
        client,
        verifier_callback        
    )
    pprint.pprint({"pump":pump.__dict__})
    pprint.pprint({"after pump":client.__dict__})
    client.register()
    pprint.pprint({"client after register":client.__dict__})


    
    me = pump.Person(webfinger)
    pprint.pprint(me.__dict__)
    #inbox = me.inbox[:100]
    #print("looking at inbox")
    #pprint.pprint(inbox)
    #for activity in inbox:
    #    pprint.pprint(activity)

    seen = {}
    for followee in me.following:
        print("We are following " + followee.id)
        seen[followee.id]=1


        #for followee in me.following:
        #if followee.id == :

    stars = ['greve@identi.ca',
                 'schestowitz@identi.ca',
                 'rms@identi.ca',
                 'bkuhn@identi.ca',
                 'fsf@identi.ca',
                 'joshuagay@identi.ca',
                 'glynmoody@identi.ca']
    for star in stars:
        followee = pump.Person(star)
        print("Looking who follows: " + followee.id)
        for follower in followee.followers:
            if follower.id not in seen:
                print("Following" + follower.id)
                seen[follower.id]=1
                follower.follow()
                time.sleep(1)
