#!/usr/bin/env python
import sys
sys.path.append("../asyncio")
sys.path.append("../xudd")
sys.path.append("../PyPump")
sys.path.append("../oauthlib")
sys.path.append("../requests-oauthlib")
sys.path.append("../dateutil")


import time

from xudd.hive import Hive
from xudd.tools import join_id
from pump import Pump
from controller import Controller
from ui import CLI

#from main import Pump
import time
import pprint
import pdb; 
from xudd.actor import Actor
from pypump import PyPump
from pypump.client import Client



import requests
import re
import json

r = requests.get('http://ofirehose.com/feed.json', stream=True, verify=False)
data = ""
for chunk in r.iter_content(1024):
    s = chunk.decode("utf-8")
    #print (chunk);
    data = data + s

#from StringIO import StringIO
#io = StringIO()
import pprint
d = json.loads(data)

def verifier_callback (url):
    print("Get callback" +url + "\n")
    print('Please follow the instructions at the following URL:')
    print(url)
    return input("Verifier: ") # the verifier is a string


if __name__ == "__main__":
    webfinger = sys.argv[1]
    #p = Pump(hive="tst",id="bba",webfinger=webfinger)
    #m = {}
    #p.setup(m)
    client = Client(
        webfinger,
        name="Muon",
        type="native"                
    )
    pprint.pprint({"before pump":client.__dict__})
    
    pump = PyPump(
        client,
        verifier_callback        
    )
    pprint.pprint({"pump":pump.__dict__})
    pprint.pprint({"after pump":client.__dict__})
    client.register()
    pprint.pprint({"client after register":client.__dict__})


    
    me = pump.Person(webfinger)
    pprint.pprint(me.__dict__)
    #inbox = me.inbox[:100]
    #print("looking at inbox")
    #pprint.pprint(inbox)
    #for activity in inbox:
    #    pprint.pprint(activity)

    seen = {}
    for followee in me.following:
        print("We are following " + followee.id)
        seen[followee.id]=1


        #for followee in me.following:
        #if followee.id == :

#een = {}

for x in d['items']:
    url = x['actor']['id']
    url2 = url.replace("acct:","")

    if url not in seen:
        print ("Adding" + url)
        seen[url]=1
        followee = pump.Person(url)
        followee.follow()
        time.sleep(3)
